### PR TITLE
Added projects and users api

### PR DESCRIPTION
**Pull request by ramakantar**

### CODE REVIEW

**Comment by Colstuwjx** [comment]
Looks good to me, could you fix the go lint issue?

**Comment by ramakantar** [comment]
Fixed linting

**Comment by Colstuwjx** [comment]
Could you add the new endpoints examples and test cases for test coverage?

**Comment by ramakantar** [comment]
Working on it.

**Comment by mauromedda** [comment]
Hi @ramakantar, in order to add test case you need to work on three point:
* add a new test function in the ${filename}_test.go file
* add mocked data for the API response (https://github.com/Colstuwjx/awx-go/tree/master/internal/mockserver/mockdata)
* add an handler for the API in the https://github.com/Colstuwjx/awx-go/blob/master/internal/mockserver/mockserver.go file

**Pull request closed without merging**
